version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip"
      - "unzip terraform_0.12.23_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - "cd terraform"
      - "ls -larths"
      - terraform init
      - terraform validate

  build:
    commands:
      ### terraform apply -var-file=terraform.tfvars --auto-approve
      - terraform apply -var-file=../terraform.tfvars -auto-approve

  post_build:
    commands:
      - echo terraform infastructure completed on `date`
